# -*- coding: utf-8 -*-
"""AIDI2004_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bhopXqErFY2GmAdQlrl3-4akPSYBPNwm
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import pickle

X, y = load_breast_cancer(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

log_clf = LogisticRegression()

log_clf.fit(X_train, y_train)

filename = 'log_clf.sav'
pickle.dump(log_clf, open(filename, 'wb'))

loaded_model = pickle.load(open(filename, 'rb'))
y_pred = loaded_model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, y_train)
filename = 'knn_clf.sav'
pickle.dump(knn_clf, open(filename, 'wb'))
loaded_model = pickle.load(open(filename, 'rb'))
y_pred = loaded_model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)